# question_bank.py

QUESTIONS = [
    # --- Geography ---
    {"q": "What is the capital of France?", "a": "Paris", "category": "Geography"},
    {"q": "Mount Everest is on the border of which two countries?", "a": "Nepal and China", "category": "Geography"},
    {"q": "Which U.S. state is nicknamed the Sunshine State?", "a": "Florida", "category": "Geography"},
    {"q": "What country is also called Holland?", "a": "Netherlands", "category": "Geography"},
    {"q": "Which two countries share the longest international border?", "a": "United States and Canada",
     "category": "Geography"},

    # --- History ---
    {"q": "In what year did the United States declare independence?", "a": "1776", "category": "History"},
    {"q": "Who was the first President of the United States?", "a": "George Washington", "category": "History"},
    {"q": "Who wrote the Declaration of Independence?", "a": "Thomas Jefferson", "category": "History"},
    {"q": "What year did World War II end?", "a": "1945", "category": "History"},

    # --- Science ---
    {"q": "What is H2O commonly known as?", "a": "Water", "category": "Science"},
    {"q": "How many bones are in the adult human body?", "a": "206", "category": "Science"},
    {"q": "What gas do plants absorb from the atmosphere?", "a": "Carbon dioxide", "category": "Science"},

    # --- Movies & TV ---
    {"q": "What 1997 film stars Will Smith and Tommy Lee Jones as agents who police aliens?", "a": "Men in Black", "category": "Movies & TV"},
    {"q": "What’s the name of the wizarding school in Harry Potter?", "a": "Hogwarts", "category": "Movies & TV"},

    # --- Sports ---
    {"q": "How many players are on the field for one soccer team?", "a": "11", "category": "Sports"},
    {"q": "How many holes are played in a standard round of golf?", "a": "18", "category": "Sports"},

    # --- General ---
    {"q": "What is the largest organ of the human body by weight?", "a": "Skin", "category": "General"},
    {"q": "What does URL stand for?", "a": "Uniform Resource Locator", "category": "General"},

    # Pop Culture
    {"q": "What is Taylor Swift’s fanbase called?", "a": "Swifties", "category": "Pop Culture"},
    {"q": "Who plays Iron Man in the MCU?", "a": "Robert Downey Jr.", "category": "Pop Culture"},
    {"q": "What Netflix show features the Upside Down?", "a": "Stranger Things", "category": "Pop Culture"},
    {"q": "Finish the brand: Ben & ____", "a": "Jerry's", "category": "Pop Culture"},
    {"q": "What 2016 mobile game had players catching creatures in AR?", "a": "Pokémon Go", "category": "Pop Culture"},
    {"q": "Which Kitchen Nightmares celebrity chef is also one of the judges on MasterChef?", "a": "Gordon Ramsay",
     "category": "Pop Culture"},
    {"q": "What candy brand encourages people to 'taste the rainbow'?", "a": "Skittles", "category": "Pop Culture"},
    {"q": "Restaurants serving up bibimbap, tteokbokki, and japchae have spread all over the world, but where do these dishes originate?", "a": "Korea", "category": "Pop Culture"},
    {"q": "Who is the author of the cookbook 'Salt, Fat, Acid, Heat'?", "a": "Samin Nosrat", "category": "Pop Culture"},
    {"q": "What cooking method involves submerging food in a water bath at a precise temperature?", "a": "Sous vide", "category": "Pop Culture"},
    {"q": "Who is known as the Barefoot Contessa?", "a": "Ina Garten", "category": "Pop Culture"},
    {"q": "What type of cuisine is the focus of the show 'The Great British Bake Off'?", "a": "British baking", "category": "Pop Culture"},
    {"q": "Which chef is known for the catchphrase 'Bam!'?", "a": "Emeril Lagasse", "category": "Pop Culture"},
    {"q": "Who is the celebrity chef known for the cooking show '30-Minute Meals'?", "a": "Rachael Ray", "category": "Pop Culture"},
    {"q": "Which reality cooking show is centered around contestants with poor cooking skills?", "a": "Worst Cooks in America", "category": "Pop Culture"},
    {"q": "What famous chef is known for his 'Naked Chef' persona and is the author of multiple cookbooks?", "a": "Jamie Oliver", "category": "Pop Culture"},
    {"q": "Which cooking show has 47 Primetime Emmy nominations and two Emmy wins?", "a": "Top Chef", "category": "Pop Culture"},
    {"q": "Who was the winner of The Great British Bake Off Season 1?", "a": "Edd Kimber", "category": "Pop Culture"},
    {"q": "What snack is Eleven obsessed with in Stranger Things?", "a": "Eggo waffles", "category": "Pop Culture"},
    {"q": "What is Joey Tribbiani's famous line about sharing food in Friends?", "a": "Joey doesn't share food.", "category": "Pop Culture"},
    {"q": "What is the favorite food of the famous cartoon cat Garfield?", "a": "Lasagna", "category": "Pop Culture"},
    {"q": "In Squid Game, what candy was used in a game that required contestants to extract a shape without breaking it?", "a": "Dalgona", "category": "Pop Culture"},
    {"q": "Which TikTok-famous whipped drink went viral during the pandemic?", "a": "Dalgona Coffee", "category": "Pop Culture"},
    {"q": "In the movie 'Sinners', which food item is used to defeat a vampire?", "a": "Garlic", "category": "Pop Culture"},
    {"q": "What is Deadpool famously known to love eating in the comics and movies?", "a": "Chimichangas", "category": "Pop Culture"},
    {"q": "What is widely considered the most popular food served at Super Bowl parties in the U.S.?", "a": "Chicken wings", "category": "Pop Culture"},
    {"q": "Which food is the top seller at July 4th BBQs and cookouts in the U.S.?", "a": "Hot dogs", "category": "Pop Culture"},
    {"q": "Which ingredient was crowned the 'flavor of the year' for 2025?", "a": "Brown sugar", "category": "Pop Culture"},
    {"q": "Which chef launched a book titled 'The Choi of Cooking' in 2025?", "a": "Roy Choi", "category": "Pop Culture"},
    {"q": "Which cookbook by Pamela Anderson was nominated for a 2025 James Beard Media Award?", "a": "I Love You: Recipes From the Heart", "category": "Pop Culture"},
    {"q": "Which artist's album 'Lemonade' won the Best Urban Contemporary Album at the 2017 Grammy Awards?", "a": "Beyoncé", "category": "Pop Culture"},
    {"q": "Which 2016 film, based on the life of three African American women mathematicians at NASA, was nominated for three Oscars?", "a": "Hidden Figures", "category": "Pop Culture"},
    {"q": "Who wrote the book 'The Souls of Black Folk,' a seminal work in African American literature?", "a": "W.E.B. Du Bois", "category": "Pop Culture"},
    {"q": "Who was the first African American to win the Masters Tournament in golf?", "a": "Tiger Woods", "category": "Pop Culture"},
    {"q": "Which sitcom, airing from 1984 to 1992, was centered around the Huxtable family?", "a": "The Cosby Show", "category": "Pop Culture"},
    {"q": "This pop superstar's 'Midnight Sky' and 'Flowers' hit the top of the charts, marking her dominance in 2024 with both powerful ballads and pop anthems.", "a": "Miley Cyrus", "category": "Pop Culture"},
    {"q": "This animated series, created by Matt Groening, has been on the air since 1989 and follows a dysfunctional family in the town of Springfield.", "a": "The Simpsons", "category": "Pop Culture"},
    {"q": "This 2009 science fiction epic, directed by James Cameron, features blue-skinned humanoids called Na'vi living on the alien planet Pandora.", "a": "Avatar", "category": "Pop Culture"},
    {"q": "Dwayne Johnson, Cristiano Ronaldo, and Selena Gomez all have millions of followers on Instagram, but which one has the most?", "a": "Cristiano Ronaldo", "category": "Celebrities"},
    {"q": "What actress has a habit of falling over on big occasions, most famously on her way to collect her first Oscar?", "a": "Jennifer Lawrence", "category": "Celebrities"},
    {"q": "Which two American Idol judges had such a toxic relationship that one allegedly threatened to shoot the other?", "a": "Nicki Minaj and Mariah Carey", "category": "Celebrities"},
    {"q": "What is the real name of the actress known as Lady Gaga?", "a": "Stefani Joanne Angelina Germanotta", "category": "Celebrities"},
    {"q": "Which actor played Jack Dawson in 'Titanic'?", "a": "Leonardo DiCaprio", "category": "Celebrities"},
    {"q": "What is the name of Oprah Winfrey’s production company?", "a": "Harpo Productions", "category": "Celebrities"},
    {"q": "What is Eminem’s real name?", "a": "Marshall Mathers", "category": "Celebrities"},
    {"q": "This famous actor had a rap persona called 'Lil' Timmy Tim' in high school.", "a": "Timothee Chalamet", "category": "Celebrities"},
    {"q": "These two actors who played Spider-Man grew up less than 10 miles away from each other.", "a": "Andrew Garfield and Tom Holland", "category": "Celebrities"},
    {"q": "This famous Emma’s real name is actually Emily.", "a": "Emma Stone", "category": "Celebrities"},
    {"q": "What is Whoopi Goldberg’s real name?", "a": "Caryn Elaine Johnson", "category": "Celebrities"},
    {"q": "Who won the People’s title of 'Sexiest Man Alive' in 2024?", "a": "John Krasinski", "category": "Celebrities"},
    {"q": "Which tech entrepreneur named his son X Æ A-12?", "a": "Elon Musk", "category": "Celebrities"},
    {"q": "Which singer is the most Grammy-nominated of all time?", "a": "Beyoncé", "category": "Celebrities"},
    {"q": "In 'Keeping Up with the Kardashians', who mistakenly referred to a pig as a chicken, resulting in a hilarious moment?", "a": "Kylie Jenner or Kylie", "category": "Celebrities"},
    {"q": "Which artist went viral on TikTok with the song 'Say So'?", "a": "Doja Cat", "category": "Celebrities"},
    {"q": "Before her rise to superstardom, Zendaya was a contestant on which dance reality show?", "a": "Dancing With the Stars", "category": "Celebrities"},
    {"q": "Which famous chef is known for his catchphrase 'Bam!'?", "a": "Emeril Lagasse", "category": "Celebrities"},
    {"q": "What rapper was also known by the nickname Slim Shady?", "a": "Eminem", "category": "Celebrities"},
    {"q": "Which Turkish shooter went viral as the 'Hitman' at the Paris Olympics for his relaxed attitude and minimal gear?", "a": "Yusuf Dikec", "category": "Celebrities"},
    {"q": "Which DJ is popular for producing EDM hits and wearing a hoodie on stage?", "a": "Alan Walker", "category": "Celebrities"},
    {"q": "Which celebrity chef gained millions of followers with ASMR-style 'Salt Bae' seasoning moves?", "a": "Nusret Gökçe", "category": "Celebrities"},
    {"q": "Who became the youngest actress ever to win an EGOT (Emmy, Grammy, Oscar, and Tony)?", "a": "Jennifer Hudson", "category": "Celebrities"},
    {"q": "Who won the Oscar for Best Actress in 2025?", "a": "Mikey Madison", "category": "Celebrities"},
    {"q": "Who won her first Emmy in 2025 for her Netflix halftime show costumes?", "a": "Beyoncé", "category": "Celebrities"},
    {"q": "Who walked the Academy Awards red carpet in a swan dress, stopping at one point to lay an egg?", "a": "Bjork", "category": "Fashion and Trends"},
    {"q": "Which fashion designer was responsible for the 'New Look' that rocked the post-war 1940s?", "a": "Christian Dior", "category": "Fashion and Trends"},
    {"q": "If you saw the acronym LBD in a fashion magazine, what would it most likely refer to?", "a": "Little black dress", "category": "Fashion and Trends"},
    {"q": "What animal appears on both the Porsche and Ferrari logo?", "a": "Horse", "category": "Fashion and Trends"},
    {"q": "What annual fashion extravaganza has seen Katy Perry arrive as a chandelier, Rihanna in a pancake-like gown by Guo Pei, and Jared Leto dressed as a big furry cat?", "a": "The Met Gala", "category": "Fashion and Trends"},
    {"q": "Who is the designer behind the fashion brand Chanel?", "a": "Coco Chanel", "category": "Fashion and Trends"},
    {"q": "Which fashion magazine is known for its September issue?", "a": "Vogue", "category": "Fashion and Trends"},
    {"q": "Which brand is known for its red-soled high heels?", "a": "Christian Louboutin", "category": "Fashion and Trends"},
    {"q": "What is the name of the fashion competition show hosted by Heidi Klum?", "a": "Project Runway", "category": "Fashion and Trends"},
    {"q": "What is the term for a model’s final walk at a fashion show?", "a": "Finale", "category": "Fashion and Trends"},
    {"q": "Which luxury brand was originally founded as a glove-making company before expanding into other accessories and ready-to-wear?", "a": "Hermès", "category": "Fashion and Trends"},
    {"q": "Which luxury brand officially launched the first-ever virtual influencer model for its 2022 campaign?", "a": "Balenciaga", "category": "Fashion and Trends"},
    {"q": "Which luxury bag is known to be an investment better than gold?", "a": "Hermès Birkin", "category": "Fashion and Trends"},
    {"q": "What is Pantone’s Color of the Year for 2025?", "a": "Mocha Mousse", "category": "Fashion and Trends"},
    {"q": "What is the name of Angelina Jolie’s fashion venture that focuses on sustainable clothing?", "a": "Atelier Jolie", "category": "Fashion and Trends"},
    {"q": "What was the theme of the Met Gala 2025?", "a": "Superfine: Tailoring Black Style (dress code: 'Tailored for You')", "category": "Fashion and Trends"},
    {"q": "Which actor described the 2025 Met Gala as a 'protest' and wore a symbolic outfit featuring ornate brooches?", "a": "Jeff Goldblum", "category": "Fashion and Trends"},
    {"q": "Which 2013 dating app was so selective that it matches you only with shared Facebook friends—Hinge, Tinder, Bumble, or Blendr?", "a": "Hinge", "category": "Tech"},
    {"q": "What space transportation company founded in 2002 by Elon Musk built Falcon 9, the first rocket completely developed in the 21st century?", "a": "SpaceX", "category": "Tech"},
    {"q": "What app is identified by a little ghost mascot, drawn up by its CEO in 2011?", "a": "Snapchat", "category": "Tech"},
    {"q": "What device with a scroll wheel was launched in 2001 with the tag '1,000 songs in your pocket'?", "a": "iPod", "category": "Tech"},
    {"q": "What is the official app store for the Android operating system?", "a": "Google Play", "category": "Tech"},
    {"q": "Which question-and-answer site was co-founded by two former Facebook employees in 2010?", "a": "Quora", "category": "Tech"},
    {"q": "What are the common programming languages that are synonymous with (a) an island in Asia, (b) a snake, (c) a gemstone?", "a": "Java, Python, Ruby", "category": "Tech"},
    {"q": "Which security vulnerability has been discovered in a popular messaging app?", "a": "Pegasus spyware", "category": "Tech"},
    {"q": "Which country has passed a law regulating the use of artificial intelligence?", "a": "European Union", "category": "Tech"},
    {"q": "Which pop culture AI assists Tony Stark in managing his Iron Man suit in the Marvel Cinematic Universe?", "a": "JARVIS", "category": "Tech"},
    {"q": "What is the name of the first computer bug?", "a": "Moth", "category": "Tech"},
    {"q": "Which AI technology is used to power virtual assistants like Siri and Alexa?", "a": "Natural language processing", "category": "Tech"},
    {"q": "Which AI-powered chatbot has recently become the most downloaded app?", "a": "ChatGPT", "category": "Tech"},
    {"q": "In which movie does Scarlett Johansson’s character interact with an advanced AI operating system?", "a": "Her", "category": "Tech"},
    {"q": "Which company offered the first commercial flights for space tourism?", "a": "Virgin Galactic", "category": "Tech"},
    {"q": "Which sports star is arguably more famous for shouting 'You cannot be serious!' at referees than for his tennis achievements?", "a": "John McEnroe", "category": "Sports and Athletes"},
    {"q": "Which of these countries does not have an animal as its national rugby logo—South Africa, Australia, or New Zealand?", "a": "New Zealand", "category": "Sports and Athletes"},
    {"q": "Every year the Super Bowl features a halftime show by a legendary act, but 2023’s show attracted more than 120 million viewers, setting a new record. Who headlined?", "a": "Rihanna", "category": "Sports and Athletes"},
    {"q": "What was the name of the gold-medal-winning Olympian who retired from professional swimming to take up acting, starring in the 1932 version of Tarzan?", "a": "Johnny Weissmuller", "category": "Sports and Athletes"},
    {"q": "Several sports legends appeared in the Amy Schumer-starring movie 'Trainwreck'. Which of these was not among them: Michael Jordan, LeBron James, or John Cena?", "a": "Michael Jordan", "category": "Sports and Athletes"},
    {"q": "Who holds the record for the most home runs in a single MLB season?", "a": "Barry Bonds", "category": "Sports and Athletes"},
    {"q": "Which country won the FIFA World Cup in 2022?", "a": "Argentina", "category": "Sports and Athletes"},
    {"q": "Who is known as 'The Greatest of All Time' in boxing?", "a": "Muhammad Ali", "category": "Sports and Athletes"},
    {"q": "What is the nickname of the New Zealand national rugby team?", "a": "All Blacks", "category": "Sports and Athletes"},
    {"q": "Who holds the record for the most Olympic gold medals?", "a": "Michael Phelps", "category": "Sports and Athletes"},
    {"q": "Which soccer player is the all-time top scorer for both Argentina and FC Barcelona?", "a": "Lionel Messi", "category": "Sports and Athletes"},
    {"q": "Which team won the 2024 Super Bowl, marking their third championship in franchise history?", "a": "Kansas City Chiefs", "category": "Sports and Athletes"},
    {"q": "Which Formula 1 driver secured the 2024 World Championship, marking his fifth title in a dominant season?", "a": "Max Verstappen", "category": "Sports and Athletes"},
    {"q": "Which Turkish shooter gained viral fame as the 'Hitman' at the Paris Olympics for his relaxed attitude and minimal gear?", "a": "Yusuf Dikec", "category": "Sports and Athletes"},
    {"q": "Which country has won the most FIFA World Cup titles?", "a": "Brazil", "category": "Sports and Athletes"},
    {"q": "Who won Super Bowl LIX in 2025?", "a": "Philadelphia Eagles", "category": "Sports and Athletes"},
    {"q": "Which country won gold at the 2025 Ice Hockey World Championship?", "a": "USA", "category": "Sports and Athletes"},
    {"q": "Which golfer passed $100 million in PGA Tour earnings in 2025?", "a": "Scottie Scheffler", "category": "Sports and Athletes"},
    {"q": "Which sports star is arguably more famous for shouting 'You cannot be serious!' at referees than for his tennis achievements?", "a": "John McEnroe", "category": "Sports and Athletes"},
    {"q": "Which of these countries does not have an animal as its national rugby logo—South Africa, Australia, or New Zealand?", "a": "New Zealand", "category": "Sports and Athletes"},
    {"q": "Every year the Super Bowl features a halftime show by a legendary act, but 2023’s show attracted more than 120 million viewers, setting a new record. Who headlined?", "a": "Rihanna", "category": "Sports and Athletes"},
    {"q": "What was the name of the gold-medal-winning Olympian who retired from professional swimming to take up acting, starring in the 1932 version of Tarzan?", "a": "Johnny Weissmuller", "category": "Sports and Athletes"},
    {"q": "Several sports legends appeared in the Amy Schumer-starring movie 'Trainwreck'. Which of these was not among them: Michael Jordan, LeBron James, or John Cena?", "a": "Michael Jordan", "category": "Sports and Athletes"},
    {"q": "Who holds the record for the most home runs in a single MLB season?", "a": "Barry Bonds", "category": "Sports and Athletes"},
    {"q": "Which country won the FIFA World Cup in 2022?", "a": "Argentina", "category": "Sports and Athletes"},
    {"q": "Who is known as 'The Greatest of All Time' in boxing?", "a": "Muhammad Ali", "category": "Sports and Athletes"},
    {"q": "What is the nickname of the New Zealand national rugby team?", "a": "All Blacks", "category": "Sports and Athletes"},
    {"q": "Who holds the record for the most Olympic gold medals?", "a": "Michael Phelps", "category": "Sports and Athletes"},
    {"q": "Which soccer player is the all-time top scorer for both Argentina and FC Barcelona?", "a": "Lionel Messi", "category": "Sports and Athletes"},
    {"q": "Which team won the 2024 Super Bowl, marking their third championship in franchise history?", "a": "Kansas City Chiefs", "category": "Sports and Athletes"},
    {"q": "Which Formula 1 driver secured the 2024 World Championship, marking his fifth title in a dominant season?", "a": "Max Verstappen", "category": "Sports and Athletes"},
    {"q": "Which Turkish shooter gained viral fame as the 'Hitman' at the Paris Olympics for his relaxed attitude and minimal gear?", "a": "Yusuf Dikec", "category": "Sports and Athletes"},
    {"q": "Which country has won the most FIFA World Cup titles?", "a": "Brazil", "category": "Sports and Athletes"},
    {"q": "Who won Super Bowl LIX in 2025?", "a": "Philadelphia Eagles", "category": "Sports and Athletes"},
    {"q": "Which country won gold at the 2025 Ice Hockey World Championship?", "a": "USA", "category": "Sports and Athletes"},
    {"q": "Which golfer passed $100 million in PGA Tour earnings in 2025?", "a": "Scottie Scheffler", "category": "Sports and Athletes"},
    {"q": "Which company manufactured the Game Boy?", "a": "Nintendo", "category": "Video Games"},
    {"q": "Ocarina of Time, Majora’s Mask, and Twilight Princess are all entries in which game series?", "a": "The Legend of Zelda", "category": "Video Games"},
    {"q": "What is an MMORPG?", "a": "Massively multiplayer online role-playing game", "category": "Video Games"},
    {"q": "Name the hero of the iconic Mass Effect games who fights the Reapers to prevent the extinction of all organic life in the galaxy.", "a": "Commander Shepard", "category": "Video Games"},
    {"q": "Gamers8: The Land of Heroes is the world’s largest esports festival, boasting a prize pool of $45 million in 2023—held in which country?", "a": "Saudi Arabia", "category": "Video Games"},
    {"q": "Which video game series features a post-apocalyptic world with vaults?", "a": "Fallout", "category": "Video Games"},
    {"q": "What is the name of the virtual reality game system developed by Sony?", "a": "PlayStation VR", "category": "Video Games"},
    {"q": "Which game popularized the battle royale genre?", "a": "PlayerUnknown's Battlegrounds (PUBG)", "category": "Video Games"},
    {"q": "What is the title of the action RPG developed by Guerrilla Games, set in a post-apocalyptic world where players control Aloy?", "a": "Horizon Zero Dawn", "category": "Video Games"},
    {"q": "Who is the creator of 'Minecraft'?", "a": "Markus 'Notch' Persson", "category": "Video Games"},
    {"q": "After how many years is Rockstar Games releasing Grand Theft Auto 6?", "a": "12 years", "category": "Video Games"},
    {"q": "Which game had the biggest in-game concert with performances from artists like Snoop Dogg, Ice Spice, and Eminem?", "a": "Fortnite", "category": "Video Games"},
    {"q": "What is the virtual currency used in Roblox?", "a": "Robux", "category": "Video Games"},
    {"q": "Which 'Call of Duty' game was the first to introduce the 'Zombies' mode?", "a": "Call of Duty: World at War (2008)", "category": "Video Games"},
    {"q": "What is the name of the Archon that rules Mondstadt in Genshin Impact?", "a": "Venti", "category": "Video Games"},
    {"q": "What planet did Superman originally hail from?", "a": "Krypton", "category": "Comics and Superheroes"},
    {"q": "What was Wonder Woman’s alter ego?", "a": "Diana Prince", "category": "Comics and Superheroes"},
    {"q": "Name the cherished comic book creator who co-created characters such as Spider-Man, Black Panther, and Thor, and appeared in every single Marvel movie up until his death.", "a": "Stan Lee", "category": "Comics and Superheroes"},
    {"q": "'JLA/Avengers' is a comic limited series that saw characters from which two major comic publishers cross over?", "a": "DC and Marvel", "category": "Comics and Superheroes"},
    {"q": "What is the Japanese equivalent of comics called?", "a": "Manga", "category": "Comics and Superheroes"},
    {"q": "Who created the character of Spider-Man?", "a": "Stan Lee and Steve Ditko", "category": "Comics and Superheroes"},
    {"q": "What is the real name of Batman?", "a": "Bruce Wayne", "category": "Comics and Superheroes"},
    {"q": "Which comic book company publishes the 'X-Men' series?", "a": "Marvel Comics", "category": "Comics and Superheroes"},
    {"q": "What is the name of Wonder Woman’s homeland?", "a": "Themyscira", "category": "Comics and Superheroes"},
    {"q": "Who are the members of the original Avengers team?", "a": "Iron Man, Thor, Hulk, Ant-Man, and Wasp", "category": "Comics and Superheroes"},
    {"q": "Which villain is considered Batman’s arch-nemesis?", "a": "The Joker", "category": "Comics and Superheroes"},
    {"q": "In the Marvel universe, what is the real name of the Scarlet Witch?", "a": "Wanda Maximoff", "category": "Comics and Superheroes"},
    {"q": "Which member of the Justice League has the ability to talk to fish?", "a": "Aquaman", "category": "Comics and Superheroes"},
    {"q": "What is the real identity of the antihero known as Deadpool?", "a": "Wade Wilson", "category": "Comics and Superheroes"},
    {"q": "Which superhero has the ability to manipulate time, and is a member of the Justice League?", "a": "The Flash", "category": "Comics and Superheroes"},
    {"q": "Who plays Cassandra Nova in the upcoming 'Deadpool & Wolverine' movie?", "a": "Emma Corrin", "category": "Comics and Superheroes"},
    {"q": "What unique ability does Miles Morales show in 'Ultimate Spider-Man: Incursion'?", "a": "Venom blast", "category": "Comics and Superheroes"},
    {"q": "Who plays Reed Richards in Marvel’s 2025 'Fantastic Four' movie?", "a": "Pedro Pascal", "category": "Comics and Superheroes"},
    {"q": "What actor voices Spider-Man Noir in the new 2025 live-action series?", "a": "Nicolas Cage", "category": "Comics and Superheroes"},
    {"q": "Which sci-fi action sequel had a killer AI doll?", "a": "M3GAN 2.0", "category": "Comics and Superheroes"},

    # Music
    {"q": "Name the song from its lyrics: “Sick and tired of hearing all these people talk about what’s the deal with this pop life and when is it gonna fade out?”", "a": "Pop by NSYNC", "category": "Music"},
    {"q": "What song has spent the most weeks atop the Billboard Hot 100?", "a": "Old Town Road", "category": "Music"},
    {"q": "Which band’s album cover features a baby floating in a swimming pool?", "a": "Nirvana", "category": "Music"},
    {"q": "Many of Taylor Swift’s songs are rumored to be about famous ex-boyfriends, but which man is “Back to December” a tribute to?", "a": "Taylor Lautner", "category": "Music"},
    {"q": "Courteney Cox’s big break didn’t come in a movie or a TV show, but in a music video for which musician?", "a": "Bruce Springsteen", "category": "Music"},
    {"q": "Who is known as the “King of Pop”?", "a": "Michael Jackson", "category": "Music"},
    {"q": "What was the Beatles’ first number one hit in the United States?", "a": "I Want to Hold Your Hand", "category": "Music"},
    {"q": "Which artist released the album “Lemonade”?", "a": "Beyoncé", "category": "Music"},
    {"q": "Who sang the hit song “Shape of You”?", "a": "Ed Sheeran", "category": "Music"},
    {"q": "Which band is known for the album “Dark Side of the Moon”?", "a": "Pink Floyd", "category": "Music"},
    {"q": "Which K-pop group was the first to perform at Coachella?", "a": "BLACKPINK", "category": "Music"},
    {"q": "Which viral TikTok sound recently dominated music charts?", "a": "Blissful Chaos by The Sound Collective", "category": "Music"},
    {"q": "Which artist inspired the Brat Summer trend?", "a": "Charli XCX", "category": "Music"},
    {"q": "Which song has the lyrics, “I’m working late, ’cause I’m a singer”?", "a": "Espresso by Sabrina Carpenter", "category": "Music"},
    {"q": "Which artist sang “Birds of a Feather”?", "a": "Billie Eilish", "category": "Music"},
    {"q": "Which song by Mariah Carey becomes popular right before Christmas every year?", "a": "All I Want for Christmas Is You", "category": "Music"},
    {"q": "What is the title of Coldplay’s tenth studio album, released in October 2024?", "a": "Moon Music", "category": "Music"},
    {"q": "Who released the chart-topping song “Gasolina”?", "a": "Daddy Yankee", "category": "Music"},
    {"q": "Which rap song holds the record for winning the most Grammy Awards?", "a": "Not Like Us by Kendrick Lamar", "category": "Music"},
    {"q": "Which artist won the most Grammys in 2025?", "a": "Kendrick Lamar", "category": "Music"},
    {"q": "What was NewJeans’ hit single released in early 2025 that went viral on TikTok?", "a": "Bubble Pop Electric", "category": "Music"},
    {"q": "What is the special name Lady Gaga uses for her fandom?", "a": "Little Monsters", "category": "Music"},
    {"q": "What song does Max listen to in Stranger Things to escape Vecna’s curse?", "a": "Running Up That Hill", "category": "Music"},
    {"q": "Which Adele hit was reimagined as a classical string piece in Bridgerton?", "a": "Someone Like You", "category": "Music"},
    {"q": "Which female rapper released the album Pink Friday?", "a": "Nicki Minaj", "category": "Music"},
    {"q": "Who topped the Billboard Hot 100 for the longest stretch in 2025?", "a": "Kendrick Lamar (Not Like Us)", "category": "Music"},
    {"q": "Which song reigned at No. 1 on the Billboard Hot 100 for 10 non-consecutive weeks in 2025?", "a": "Ordinary by Alex Warren", "category": "Music"},
    {"q": "Which 2025 single by Calvin Harris features Clementine Douglas?", "a": "Blessings", "category": "Music"},
    {"q": "Which 2025 hit by Kendrick Lamar and SZA topped the Billboard Hot 100 for weeks?", "a": "Luther", "category": "Music"},

    # K-Pop and Dramas
    {"q": "Who is the leader of the K-pop group BTS?", "a": "RM", "category": "K-Pop and Dramas"},
    {"q": "Which K-pop group has a sub-unit named Odd Eye Circle?", "a": "LOONA", "category": "K-Pop and Dramas"},
    {"q": "What is the name of the first album released by BTS?", "a": "2 Cool 4 Skool", "category": "K-Pop and Dramas"},
    {"q": "What is the fandom name of GFriend?", "a": "Buddy", "category": "K-Pop and Dramas"},
    {"q": "What does the acronym “BTS” stand for?", "a": "Bangtan Sonyeondan (Bulletproof Boy Scouts)", "category": "K-Pop and Dramas"},
    {"q": "What is the name of BTS’s international fan group?", "a": "ARMY", "category": "K-Pop and Dramas"},
    {"q": "What is the name of BLACKPINK’s official fandom?", "a": "Blink", "category": "K-Pop and Dramas"},
    {"q": "Which K-pop band was the first to take the stage at the Grammys?", "a": "BTS", "category": "K-Pop and Dramas"},
    {"q": "Who is known as the “King of K-pop”?", "a": "G-Dragon", "category": "K-Pop and Dramas"},
    {"q": "In “Crash Landing on You,” where does the female lead, Yoon Se-ri, accidentally land?", "a": "North Korea", "category": "K-Pop and Dramas"},
    {"q": "What are the rich people who watch ‘Squid Game’ referred to as in the show?", "a": "VIPs", "category": "K-Pop and Dramas"},
    {"q": "Where do the main characters from Crash Landing on You meet annually?", "a": "Switzerland", "category": "K-Pop and Dramas"},
    {"q": "In Pinocchio, what happens to the lead character, Choi In-ha, when she lies?", "a": "Uncontrollable hiccups", "category": "K-Pop and Dramas"},
    {"q": "In Squid Game, what is the main prize for the last person standing in the deadly game?", "a": "45.6 billion won", "category": "K-Pop and Dramas"},
    {"q": "Which K-Drama centers around a mysterious zombie outbreak set in the Joseon Dynasty?", "a": "Kingdom", "category": "K-Pop and Dramas"},
    {"q": "Which K-pop star plays Ae-Soon in When Life Gives You Tangerines?", "a": "IU", "category": "K-Pop and Dramas"},
    {"q": "Who played the female lead researcher in The Potato Lab?", "a": "Lee Sun-bin", "category": "K-Pop and Dramas"},
    {"q": "Which BLACKPINK member stars in Newtopia?", "a": "Jisoo", "category": "K-Pop and Dramas"},
    {"q": "Who was the protagonist in Weak Hero Class 2?", "a": "Yeon Si-eun (Park Ji-hoon)", "category": "K-Pop and Dramas"},
    {"q": "Resident Playbook is a spin-off of which popular medical K-drama series?", "a": "Hospital Playlist", "category": "K-Pop and Dramas"},
    {"q": "Who won the game in Squid Game Season 3?", "a": "Player 222, Jun-hee’s newborn baby", "category": "K-Pop and Dramas"},

    # Social Media
    {"q": "What recent trend has artists using virtual reality for live performances?", "a": "Metaverse concerts", "category": "Social Media"},
    {"q": "Who was one of the first celebrities to participate in the “Ice Bucket Challenge” in 2014, helping to raise awareness for ALS?", "a": "Bill Gates", "category": "Social Media"},
    {"q": "Which artist recently broke through using only social media platforms for promotion?", "a": "Lilith Voss", "category": "Social Media"},
    {"q": "Which social media platform introduced a feature where users can create 10-minute long videos?", "a": "TikTok", "category": "Social Media"},
    {"q": "Which social media app recently added a virtual reality shopping feature?", "a": "Instagram (Meta’s Virtual Storefronts)", "category": "Social Media"},
    {"q": "Which popular social media platform known for selfies was originally called Picaboo?", "a": "Snapchat", "category": "Social Media"},
    {"q": "Which social media platform has gained massive popularity among Gen Z for its anonymous Q&A feature?", "a": "BeReal", "category": "Social Media"},
    {"q": "What social media trend involves using AI-generated deepfakes for interactive storytelling?", "a": "AI Faces", "category": "Social Media"},
    {"q": "Which is one of the most commonly used emoji on social media?", "a": "😂", "category": "Social Media"},
    {"q": "Who has the most followers on Twitter?", "a": "Barack Obama", "category": "Social Media"},
    {"q": "Which is the top social media platform for shopping?", "a": "Facebook", "category": "Social Media"},
    {"q": "What is the term coined for content creators aged 60 years and above?", "a": "Granfluencers", "category": "Social Media"},
    {"q": "Which is the most widely used hashtag globally on Instagram?", "a": "#love", "category": "Social Media"},
    {"q": "Name the AI chatbot that X (formerly Twitter) recently rolled out for free to its users.", "a": "Grok", "category": "Social Media"},
    {"q": "Which platform allows users to create and follow “Boards”?", "a": "Pinterest", "category": "Social Media"},
    {"q": "What is the name of the text-based social media app launched by Meta as a competitor to Twitter?", "a": "Threads", "category": "Social Media"},
    {"q": "Which celebrity chef has the most followers on Instagram?", "a": "Gordon Ramsay", "category": "Social Media"},
    {"q": "When Amazon started out, what did it exclusively sell?", "a": "Books", "category": "Social Media"},
    {"q": "At which event did John Cena publicly praise BTS?", "a": "Fan Expo Dallas", "category": "Social Media"},
    {"q": "What is the term for AI-generated videos, images, or voices?", "a": "Deepfakes", "category": "Social Media"},


]

# Optional: you can compute the category list from the data.
CATEGORIES = sorted({q["category"] for q in QUESTIONS})
